# Generated by Django 5.0.7 on 2024-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='task',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='dedline',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='priority',
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.BooleanField(default=True),
        ),
    ]
