# Generated by Django 5.0.7 on 2024-08-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
